### ISSUE TITLE
Installing with pip

### ISSUE THREAD

**Issue by asher-pembroke** [pysat/pysatCDF#15]
I ran into problems installing with pip involving the notorious libgfortran rpath [bug](https://github.com/ContinuumIO/anaconda-issues/issues/739) on mac. 

To reproduce, 
1. pip pysatCDF on a mac anaconda/miniconda environment (python 2.7)
2. `import pysatCDF`
3. raises something like this

```console
ImportError: dlopen(/Users/apembrok/Library/Caches/Python-Eggs/pysatCDF-0.3.0-py2.7-macosx-10.6-x86_64.egg-tmp/pysatCDF/fortran_cdf.so, 2): Library not loaded: @rpath/./libgfortran.3.dylib
  Referenced from: /Users/apembrok/Library/Caches/Python-Eggs/pysatCDF-0.3.0-py2.7-macosx-10.6-x86_64.egg-tmp/pysatCDF/fortran_cdf.so
  Reason: image not found
```

To resolve:
1. verify the existing library names assigned to `fortran_cdf.so`:
`otool -L ${CONDA_PREFIX}/lib/python2.7/site-packages/pysatCDF/fortran_cdf.so`
3. modify the library names with `install_name_tool`:
```console
install_name_tool -change @rpath/./libgfortran.3.dylib ${CONDA_PREFIX}/lib/libgfortran.dylib -change @rpath/./libquadmath.0.dylib ${CONDA_PREFIX}/lib/libquadmath.0.dylib fortran_cdf.so ${CONDA_PREFIX}/lib/python2.7/site-packages/pysatCDF/fortran_cdf.so
```

Conda package installers usually fix the rpath issue automagically. Not sure how to do this with setuptools...

**Comment by rstoneback** [comment]
Thanks Asher.

Since you have the terminal command can’t you invoke that from setup.py?

I believe there is a post-install trigger in setuptools and the package has the paths and such the final code is, or will be, when installed.

On Oct 9, 2019, at 5:25 PM, Asher Pembroke <notifications@github.com<mailto:notifications@github.com>> wrote:


I ran into problems installing with pip involving the notorious libgfortran rpath bug<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FContinuumIO%2Fanaconda-issues%2Fissues%2F739&data=02%7C01%7Crstoneba%40utdallas.edu%7Ca340e93046f74b7db90808d74d07840f%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637062566996679415&sdata=rc%2FB%2FjvgNM5g9Bqqg18SM35sz%2FwZAT9A0%2BnIgCHgO%2B8%3D&reserved=0> on mac.

To reproduce,

  1.  pip pysatCDF on a mac anaconda/miniconda environment (python 2.7)
  2.  import pysatCDF
  3.  raises something like this

ImportError: dlopen(/Users/apembrok/Library/Caches/Python-Eggs/pysatCDF-0.3.0-py2.7-macosx-10.6-x86_64.egg-tmp/pysatCDF/fortran_cdf.so, 2): Library not loaded: @rpath/./libgfortran.3.dylib
  Referenced from: /Users/apembrok/Library/Caches/Python-Eggs/pysatCDF-0.3.0-py2.7-macosx-10.6-x86_64.egg-tmp/pysatCDF/fortran_cdf.so
  Reason: image not found

To resolve:

  1.  verify the existing library names assigned to fortran_cdf.so:
otool -L ${CONDA_PREFIX}/lib/python2.7/site-packages/pysatCDF/fortran_cdf.so
  2.  modify the library names with install_name_tool:

install_name_tool -change @rpath/./libgfortran.3.dylib ${CONDA_PREFIX}/lib/libgfortran.dylib -change @rpath/./libquadmath.0.dylib ${CONDA_PREFIX}/lib/libquadmath.0.dylib fortran_cdf.so ${CONDA_PREFIX}/lib/python2.7/site-packages/pysatCDF/fortran_cdf.so

Conda package installers usually fix the rpath issue automagically. Not sure how to do this with setuptools...

**Comment by rstoneback** [comment]
Thanks for the report.

Cheers

**Comment by asher-pembroke** [comment]
A lot of places suggest the [delocate tool](https://pypi.org/project/delocate/) which makes pip wheels portable. That would at least solve the issue where users aren't able to install with pip.

**Comment by asher-pembroke** [comment]
Also, note that `install_name_tool` requires users to have the xcode developer tools installed: https://stackoverflow.com/a/11598098

**Comment by rstoneback** [comment]
The delocate looks like it would be helpful for pip.

**Comment by asher-pembroke** [comment]
I found a lot of issues with clang as well, but gcc seems to work better.

I'm able to install from setup.py using the following environment setup

```console
conda create -n pysatCDF python=2.7
conda install -c anaconda gcc
conda install -c anaconda numpy
pip install pysat (or setup.py after cloning pysat)
```

Then, from pysatCDF directory:
```console
python setup.py install (or pip install .)
```
@rstoneback Anything left to do here?

**Comment by rstoneback** [comment]
Does it work in python 3? If it’s good then I think we are good.

Cheers,
Russell

On Nov 4, 2019, at 11:41 AM, Asher Pembroke <notifications@github.com> wrote:

﻿

I found a lot of issues with clang as well, but gcc seems to work better.

I'm able to install from setup.py using the following environment setup

conda create -n pysatCDF python=2.7
conda install -c anaconda gcc
conda install -c anaconda numpy
pip install pysat (or setup.py after cloning pysat)

Then, from pysatCDF directory:

python setup.py install (or pip install .)

@rstoneback<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frstoneback&data=02%7C01%7Crstoneba%40utdallas.edu%7Cb069f242f989454df8a508d7615696cb%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637084896840415726&sdata=Bl8QmPA%2Fl4M4J42nXjrokOeJegJzySj2Via2ZNGLtug%3D&reserved=0> Anything left to do here?

**Comment by asher-pembroke** [comment]
Yep, it works with python3 as well.

**Comment by rstoneback** [comment]
I've uploaded delocated versions of pysatCDF to pypi for macosx. python 2 and 3.8 are currently supported.

**Comment by aburrell** [comment]
I was finally able to fix various issues and got pysatCDF to install on my laptop (OSX Mojave) with python 2.7, 3.7, and 3.8.

**Comment by rstoneback** [comment]
Great!
